
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { Capacitor } from '@capacitor/core';

// const SUPABASE_URL = "https://eqvgbqxaefpkbfetubrt.supabase.co";
// const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVxdmdicXhhZWZwa2JmZXR1YnJ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3NDU5MjAsImV4cCI6MjA2MzMyMTkyMH0.1Az2gg7RGJW-zR9AItfKwZy1Sd3g3WqbUslJlu5TAbo";

const SUPABASE_URL = "https://nvcgijtnwnbgxzuclbhy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im52Y2dpanRud25iZ3h6dWNsYmh5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwMTM4MjEsImV4cCI6MjA3MjU4OTgyMX0.vybd5mCZUKZccLN2toyzz9z6yoQs0FXWEaYPb4S2nck";

// Configuration adaptée pour web et mobile
const getAuthConfig = () => {
  const isNative = Capacitor.isNativePlatform();
  
  return {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: !isNative, // Désactiver sur mobile natif
  };
};

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: getAuthConfig(),
  realtime: {
    params: {
      eventsPerSecond: 1
    }
  },
  db: {
    schema: 'public'
  },
  global: {
    headers: { 
      'X-Client-Info': `lovable-web-app-${Capacitor.getPlatform()}` 
    }
  }
});

// Fonction simplifiée pour vérifier si une session est valide
export const hasValidSession = async (): Promise<boolean> => {
  try {
    const { data, error } = await supabase.auth.getSession();
    return !!data.session && !error;
  } catch (e) {
    console.error("Exception lors de la vérification de la session:", e);
    return false;
  }
};
